version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 45432:5432
    command: postgres -c max_connections=1000
    environment:
      POSTGRES_PASSWORD: hotpler1234

  redis:
    restart: always
    image: redis:6.2.6
    container_name: redis
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "46379:6379"
    volumes:
      - ./redis/data:/data
    mem_limit: 96m
    networks:
      - postgres-network

  server:
    build: ./server
    depends_on:
      - postgres
    volumes:
      - ./server:/server
    ports:
      - 43000:3000
    networks:
      - postgres-network
    # links:
    #   - postgres
volumes:
  postgres:
    driver: local
  redis:
    driver: local

networks:
  postgres-network:
    driver: bridge
